---

name: "Building OS packages with a shared workflow."

################################################################################
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - 'dev/workflow'
    tags:
      - '**'
  workflow_dispatch: {}

################################################################################
jobs:

  ###########################
  call-shared-workflow:
    name: "Calling shared build workflow"
    uses: fbrehm/actions/.github/workflows/build-python-packages.yaml@develop
    with:
      has_i18n: true
      libdir: lib/fb_vmware

# vim: et tabstop=2 expandtab shiftwidth=2 softtabstop=2 list
