---

name: "Building OS packages with a shared workflow."

################################################################################
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - 'dev/workflow'
    tags:
      - '**'
  workflow_dispatch: {}

################################################################################
jobs:

  ###########################
  call-shared-workflow:
    name: "Calling shared build workflow"
    uses: fbrehm/actions/.github/workflows/build-python-packages.yaml@develop
    with:
      has_i18n: true
      # test_python_versions: '["3.8", "3.9", "3.10", "3.11", "3.12"]'
      test_python_versions: '["3.8", "3.10", "3.11", "3.12"]'
      libdir: lib/fb_vmware
      debian_versions: 'Debian-Bullseye Debian-Bookworm Ubuntu-Focal Ubuntu-Jammy'
      additional_debian_build_packages: 'python3-fb-logging python3-fb-tools python3-pyvmomi'
    secrets:
      pypi_token: ${{ secrets.PYPI_TOKEN }}


# vim: et tabstop=2 expandtab shiftwidth=2 softtabstop=2 list
